var start=0;
var sequence=[];
var pointer=0;
var ep;
var score=0;
function playSimonByComputer()
{
    var simon_color=['red','green','blue','yellow'];
    var move=Math.floor(Math.random()*4);
    var makeSound=new Audio("sounds/yellow.mp3");
    makeSound.play();
    sequence.push(simon_color[move]);
    $('.'+simon_color[move]).addClass('pressed');
    setTimeout(function(){
    $('.'+simon_color[move]).removeClass('pressed');
    },100);

}

$(document).keypress(function () {
if(start===0)
{
$("#level-title").html("Listen the sound and reply");
start=1;
score=0;
playSimonByComputer();
}
else
{
start=0;
score=0;
pointer=0;
sequence=[];
var makeSound=new Audio("sounds/wrong.mp3");
makeSound.play();
$("#level-title").html("Game Over! Press Any Key to start [score : 0]");
}
});

$(".green").click(function(){
if(pointer==sequence.length)return;
var makeSound=new Audio("sounds/yellow.mp3");
makeSound.play();
$(".green").addClass('pressed');
setTimeout(function(){
$(".green").removeClass('pressed');
},100);
if(sequence[pointer]==='green')
{
pointer++;    
if(pointer===sequence.length)
{
score++;
pointer=0;
ep=0;
//play the previous moves generated by simon computer
intervalID=setInterval(function () {
if(ep===sequence.length)
{
clearInterval(intervalID);    
playSimonByComputer();
return;
}
var j=ep;
var makeSound=new Audio("sounds/yellow.mp3");
makeSound.play();
$('.'+sequence[j]).addClass('pressed');
setTimeout(function(){
$('.'+sequence[j]).removeClass('pressed');
},100);
ep++;
},700);
}
}
else
{
start=0;
pointer=0;
sequence=[];
var makeSound=new Audio("sounds/wrong.mp3");
makeSound.play();
$("#level-title").html("Game Over! Press Any Key to start [Score : "+score+"]");
}
});


$(".red").click(function(){
    if(pointer==sequence.length)return;
    var makeSound=new Audio("sounds/yellow.mp3");
    makeSound.play();
    $(".red").addClass('pressed');
    setTimeout(function(){
    $(".red").removeClass('pressed');
    },100);
    if(sequence[pointer]==='red')
    {
    pointer++;    
    if(pointer===sequence.length)
    {
     score++;   
    pointer=0;
    ep=0;
    //play the previous moves generated by simon computer
    intervalID=setInterval(function () {
    if(ep===sequence.length)
    {
    clearInterval(intervalID);    
    playSimonByComputer();
    return;
    }
    var j=ep;
    var makeSound=new Audio("sounds/yellow.mp3");
    makeSound.play();
    $('.'+sequence[j]).addClass('pressed');
    setTimeout(function(){
    $('.'+sequence[j]).removeClass('pressed');
    },100);
    ep++;
    },700);
    }
    }
    else
    {
    start=0;
    pointer=0;
    sequence=[];
    var makeSound=new Audio("sounds/wrong.mp3");
    makeSound.play();
    $("#level-title").html("Game Over! Press Any Key to start [Score : "+score+"]");
}
    });
    


    $(".yellow").click(function(){
        if(pointer==sequence.length)return;
        var makeSound=new Audio("sounds/yellow.mp3");
        makeSound.play();
        $(".yellow").addClass('pressed');
        setTimeout(function(){
        $(".yellow").removeClass('pressed');
        },100);
        if(sequence[pointer]==='yellow')
        {
        pointer++;    
        if(pointer===sequence.length)
        {
         score++;   
        pointer=0;
        ep=0;
        //play the previous moves generated by simon computer
        intervalID=setInterval(function () {
        if(ep===sequence.length)
        {
        clearInterval(intervalID);    
        playSimonByComputer();
        return;
        }
        var j=ep;
        var makeSound=new Audio("sounds/yellow.mp3");
        makeSound.play();
        $('.'+sequence[j]).addClass('pressed');
        setTimeout(function(){
        $('.'+sequence[j]).removeClass('pressed');
        },100);
        ep++;
        },700);
        }
        }
        else
        {
        start=0;
        pointer=0;
        sequence=[];
        var makeSound=new Audio("sounds/wrong.mp3");
        makeSound.play();
        $("#level-title").html("Game Over! Press Any Key to start [Score : "+score+"]");
        }
        });
        
    


        $(".blue").click(function(){
            if(pointer==sequence.length)return;
            var makeSound=new Audio("sounds/yellow.mp3");
            makeSound.play();
            $(".blue").addClass('pressed');
            setTimeout(function(){
            $(".blue").removeClass('pressed');
            },100);
            if(sequence[pointer]==='blue')
            {
            pointer++;    
            if(pointer===sequence.length)
            {
            score++;
            pointer=0;
            ep=0;
            //play the previous moves generated by simon computer
            intervalID=setInterval(function () {
            if(ep===sequence.length)
            {
            clearInterval(intervalID);    
            playSimonByComputer();
            return;
            }
            var j=ep;
            var makeSound=new Audio("sounds/yellow.mp3");
            makeSound.play();
            $('.'+sequence[j]).addClass('pressed');
            setTimeout(function(){
            $('.'+sequence[j]).removeClass('pressed');
            },100);
            ep++;
            },700);
            }
            }
            else
            {
            start=0;
            pointer=0;
            sequence=[];
            var makeSound=new Audio("sounds/wrong.mp3");
            makeSound.play();
            $("#level-title").html("Game Over! Press Any Key to start [Score : "+score+"]");
        }
            });
            
        

/*        
$(".blue").click(function(){
    if(pointer===sequence.length)return;
    var makeSound=new Audio("sounds/yellow.mp3");
    makeSound.play();
    $(".blue").addClass('pressed');
    setTimeout(function(){
    $(".blue").removeClass('pressed');
    },100);
    if(sequence[pointer]==='blue')
    {
    pointer++;    
    if(pointer===sequence.length)
    {
    pointer=0;
    //play the previous moves generated by simon computer
    for(var i=0;i<sequence.length;i++)
    {
        var makeSound=new Audio("sounds/yellow.mp3");
        makeSound.play();
        $('.'+sequence[i]).addClass('pressed');
        setTimeout(function(){
        $('.'+sequence[i]).removeClass('pressed');
        },100);
    }
    //play the new move by simon computer
    playSimonByComputer();
    }
    }
    else
    {
    start=0;
    pointer=0;
    sequence=[];
    var makeSound=new Audio("sounds/wrong.mp3");
    makeSound.play();
    $("#level-title").html("Game Over! Press Any Key to start");
    }
    });
    
*/
    